### ISSUE TITLE
Mispelling of "Repository" in README file

### ISSUE THREAD

**Issue by Mejiabrayan** [g-cqd/Fonts#1]
I noticed a minor typographical error in the README file of this repository. The word "Repository" is misspelled as "Reposiroty" in the introductory section. It would be great to correct this to ensure clarity and professionalism.

Here is the relevant excerpt from the README file:

```plaintext
I know, you know, we know, fonts are often expansive. But it is really easy to find free official files of them. So there are so much of them here and it's not going to stop.

Full size of Downloaded Reposiroty (compressed) : ±1.38GiB
Full size of Downloaded Repository : ± 2.59GiB
Full size of Cloned Repository : ± 3.83GiB
```

I recommend updating it to:
```plaintext
I know, you know, we know, fonts are often expansive. But it is really easy to find free official files of them. So there are so many of them here and it's not going to stop.

Full size of Downloaded Repository (compressed): ±1.38GiB
Full size of Downloaded Repository: ±2.59GiB
Full size of Cloned Repository: ±3.83GiB
```

**Comment by g-cqd** [comment]
Hi @Mejiabrayan,
Thanks for noticing it.

It will be addressed soon.

**Comment by g-cqd** [comment]
Should be fixed now.

https://github.com/g-cqd/Fonts/commit/66d600a0e6d70e0620d9b9f91b442f365461e77c
